name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install MuseScore
      run: |
        wget https://github.com/musescore/MuseScore/releases/download/v4.4.3/MuseScore-Studio-4.4.3.242971445-x86_64.AppImage
        chmod +x MuseScore-Studio-4.4.3.242971445-x86_64.AppImage
        sudo ln -s MuseScore-Studio-4.4.3.242971445-x86_64.AppImage /usr/bin/mscore
    - run: npm install
    - run: QT_QPA_PLATFORM=offscreen npm test
      env:
        CI: true