name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20, 22, 24]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install MuseScore
      run: |
        sudo apt update -y
        sudo apt install -y software-properties-common libjack0 libasound2 libgl1 libglib2.0-0 libnss3 libfontconfig1 libegl1-mesa
        sudo add-apt-repository universe
        sudo apt install -y libfuse2
        wget https://github.com/musescore/MuseScore/releases/download/v4.4.3/MuseScore-Studio-4.4.3.242971445-x86_64.AppImage
        chmod +x MuseScore-Studio-4.4.3.242971445-x86_64.AppImage
        sudo ln -s $(pwd)/MuseScore-Studio-4.4.3.242971445-x86_64.AppImage /usr/bin/mscore
    - run: npm install
    - run: QT_QPA_PLATFORM=offscreen npm test
      env:
        CI: true