name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install MuseScore
      run: |
        sudo apt-get update
        sudo apt-get -y install musescore
    - run: npm install
    - run: QT_QPA_PLATFORM=offscreen npm test
      env:
        CI: true